const WEBSITE_TYPE = Object.freeze({
    IP: 1,
    OTT: 2,
    CMOT: 3
});

const DOCUMENT_TYPE = Object.freeze({
    PRODUCER_ID_PROOF: 1,
    DIRECTOR_ID_PROOF: 2,
    UNCENSORED_FILE: 3,
    DECLARATION_CLAUSE_FILE: 3,
    FILE_CBFC_CERTIFICATE: 4,
    AUTHORIZATION_LATTER: 5,
    DECLARATION_LATTER: 6,
    SYNOPSIS_IN_ENGLISH: 7,
    DIRECTORS_PROFILE: 8,
    PRODUCERS_PROFILE: 9,
    DETAILS_OF_CAST_CREW: 10,
    GOV_ID_PROOF: 11,
    PASSPORT_IMAGE: 12,
    FIRST_GOV_ID_PROOF: 13,
    SECOND_GOV_ID_PROOF: 14,
    UPLOAD_CV: 15,
    UPLOAD_REEL: 16,
    CO_PRODUCER_ID_PROOF: 17,
});

const FORM_STEPS = Object.freeze({
    FILM_DETAILS: 1,
    PRODUCERS_DETAILS: 2,
    DIRECTORS_DETAILS: 3,
    CREW_DETAILS: 4,
    CBFC_CERTIFICATION: 5,
    OTHER_DETAILS: 6,
    DOCUMENTS: 7,
    DECLARATION_PAYMENT: 8,
    SUBMISSION: 9
});

export default {
    WEBSITE_TYPE,
    DOCUMENT_TYPE,
    FORM_STEPS
}
