const FORM_STEPS = Object.freeze({
    FILM_DETAILS: 1,
    PRODUCERS_DETAILS: 2,
    DIRECTORS_DETAILS: 3,
    CREW_DETAILS: 4,
    CBFC_CERTIFICATION: 5,
    OTHER_DETAILS:6,
    DOCUMENTS:7,
    DECLARATION_PAYMENT:8,
    SUBMISSION:9
});

export default FORM_STEPS;